name: "Deploy Django"


env:
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

on:
    workflow_run:
      workflows: ["Django CI"]  # Запускаем после успешного ci.yml
      types:
        - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Запускаем только при успешном CI
    runs-on: ubuntu-latest

    steps:
      - name: Подключение к серверу и деплой
        env:
           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo systemctl stop electionbot.service voteschool.service
            cd /var/www/myprojects/ElectionArduino/Elections-Arduino-Project
            git pull origin main    
            source venv/bin/activate
            pip install -r requirements.txt
            DB_PASSWORD="$DB_PASSWORD" python ElectionServer/manage.py migrate
            sudo systemctl start voteschool.service electionbot.service
            echo "✅ Деплой успешно завершён!"