name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Включение БД??
        run: | 
           sudo systemctl start mysql.service
           sleep 5
           mysql -u root -proot -e "CREATE DATABASE elections;"

      - name: Копирование кода из репозитория
        uses: actions/checkout@v4

      - name: Установка python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Параметр установки

      - name: Установка зависимостей
        run: pip install -r requirements.txt

      - name: Запускаем миграции
        env:
          DB_PASSWORD: root
        run: python ElectionServer/manage.py migrate

      - name: Запускаем тесты
        env:
          SHA_ELECTION: ${{ secrets.SHA_ELECTION }}
          HASH_ELECTION: ${{ secrets.HASH_ELECTION }}
          DB_PASSWORD: root
        run: python ElectionServer/manage.py test ElectionServer