name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: elections
          MYSQL_USER: root
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.ROOT }}
        ports:
          - 3306/3306
        options: >-
          --name=mysql-master
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Копирование кода из репозитория
        uses: actions/checkout@v4

      - name: Установка python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Параметр установки

      - name: Установка зависимостей
        run: pip install -r requirements.txt

      - name: Запускаем миграции
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: python ElectionServer/manage.py migrate

      - name: Запускаем тесты
        env:
          SHA_ELECTION: ${{ secrets.SHA_ELECTION }}
          HASH_ELECTION: ${{ secrets.HASH_ELECTION }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: python ElectionServer/manage.py test